### ISSUE TITLE
Linux compile broken

### ISSUE THREAD

**Issue by hirdrac** [zaimoni/Cataclysm#49]
Hi - not sure if you still intend to support non-Windows/MSVC builds, but I had to make a number of changes to build on Linux.
Here's a summary of the issues I found and how I fixed them.  If you're interested in a patch for any/all of these changes, let me know.

**fatal build errors**
* includes fail on case-sensitive file systems
  - changed 'JSON.h' includes to 'json.h'
* unknown 'vsprintf_s' function
  - changed to use 'vsnprintf' instead.  (could make WIN32 builds use vsprintf_s if needed)
* various missing system includes:
  - ios_file.h: included unistd.h  for unlink(), rename()
  - line.h:     included cmath    for sqrt()
  - npc.h:    included memory    for std::unique_ptr
* use_active_item() template function references undefined game class
  - moved definition from 'player.h' to end of 'game.h'
* dist() function in overmap.cpp conflicts with dist template in line.h
  - renamed dist() function to dist_fn()
* link failure because of multiple definitions of flush_tilesheets,mvwaddbgtile,mvwaddfgtile
  - made these functions inline in wrap_curses.h
* fatal errors in main.cpp for missing OS_dir type
  - in main.cpp, replaced OS_dir::exists() calls with std::filesystem::exists()

**compile warnings**
* JASON_parse templates generate warnings for enum value comparison between different enums
  - replaced 'enum { origin = XXX }' with 'static constexpr TYPE origin = static_cast<TYPE>(XXX)'
* control reaches end of non-void function warning for invert_color() in output.cpp
  - added default case in switch statements (default to white)

**Comment by zaimoni** [comment]
Please accept my apologies for the delay.  

1) The described changes are generally ok.  I would accept a patch (or patch series) containing all of this.  Consequent dead code cleanup would be on my end.

1a) the main advantage of using vsprintf_s on WIN32 is the compile-time checking.  That said, there have been historical issues with multiple-escaping format strings (MSVC++ is fragile there).  Using WIN32 guard on vsprintf_s makes sense.

Relevant issues that were not in the tracker at the time of posting (I just created them): https://github.com/zaimoni/Cataclysm/issues/51 (template parameter packs)
https://github.com/zaimoni/Cataclysm/issues/52 (std::filesystem).  Handling these are not in scope of the patch we are discussing.

2) While I have a working MingW64 (8.1.x) install, the inherited makefile isn't really adequate (it relies too much on globbing and it's not clear how to modify it to build both Cataclysm and Socrates' Daimon , rather than materially re-implement outright.  I have considered conversion to a CMake-based build system.

**Comment by hirdrac** [comment]
I have a modified makefile that builds both the main binary and Socrates' Daimon, but some additional code changes were required for Socrates' Daimon:
* in trapdef.cpp: modified TRAPS() macros to remove 'difficulty' argument so the variable arg part of the macro always has at least one argument (MSVC++ has a non-standard feature where the trailing comma is removed in the expansion of __VA_ARGS__ if there are no arguments)

I'll see about submitting individual patches for each issue so you can review each one appropriately.

**Comment by zaimoni** [comment]
Thank you.

The intended makefile for Linux is Makefile; I'm fine with a patch outright upgrading that.  (I can study the Linux version to see how to adapt the required changes for Makefile.Windows .)

**Comment by hirdrac** [comment]
No reason you can't use the base Makefile for both Linux & MSys/MinGW.  I used Makefile.Windows as a reference for the changes I needed to make but I don't think it's needed any more.
All of my changes are in one pull request - hope that's not a problem.

**Comment by zaimoni** [comment]
All changes/one pull request with many commits:

No, not a problem (this time).  Now that I've seen how the GitHub UI works, it definitely *could* be a problem when describing the changes in this much detail, is not practical.  (I didn't see an option to "apply all commits through this one but no later".)

I'll need to see what the most popular policy options are, and review them.
